# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Will的博客
tagline:          踏实、谦虚、勤奋、上进！
url:              http://willclub.me
paginate:         1
baseurl:          /
author:
  name:           Will Mo
  url:            http://willclub.me
  email:          willmo1987@gmail.com

#Page list
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/willmo1987/willmo1987.github.io
